[package]
name = "graftpress"
version = "0.1.0"
authors = ["nilinswap <nilinswap@gmail.com>"]
edition = "2018"


[dependencies]
realm = {path = "/Users/swapnil/forgit/ackotech/realm"}
graftpress_lib = {path = "graftpress_lib"}
futures = "~0.1.26"
hyper = "~0.12.27"
http = "~0.1.17"
